name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - name: Install dependencies
        run: npm ci
      - name: Check types
        run: npx tsc --noEmit
      - name: Lint check
        run: npm run lint
      - name: Prettier check
        run: npx prettier --check .

  install:
    needs: check
    if: success()
    runs-on: ubuntu-latest
    container: cypress/browsers:node18.12.0-chrome107-ff106
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ~/.cache/Cypress
          key: cypress-${{ hashFiles('package-lock.json') }}
          restore-keys: cypress-
      - name: Install dependencies
        run: npm ci
      - name: Verify Cypress
        run: npx cypress verify
      # Pre-generate mochawesome directory to ensure proper permissions
      - name: Setup report directory
        run: |
          mkdir -p cypress/reports
          chmod -R 777 cypress/reports
      # Save the entire workspace including node_modules
      - name: Save workspace
        uses: actions/upload-artifact@v3
        with:
          name: workspace
          path: |
            .
            !.git
            !.github

  test:
    needs: install
    if: success()
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4]
        browsers: [chrome, firefox, edge]
    container: cypress/browsers:node18.12.0-chrome107-ff106
    steps:
      - name: Download workspace
        uses: actions/download-artifact@v3
        with:
          name: workspace
          path: .
      - name: Restore file permissions
        run: chmod -R +x node_modules/.bin
      - name: Run Cypress tests
        env:
          CYPRESS_AUTOMATENOW_URL: ${{ secrets.AUTOMATENOW_URL }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SPLIT: ${{ strategy.job-total }}
          SPLIT_INDEX: ${{ strategy.job-index }}
        run: npx cypress run --browser ${{ matrix.browsers }} --parallel --record --key ${{ secrets.CYPRESS_RECORD_KEY }}
      - name: Save test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results-${{ matrix.browsers }}-${{ matrix.containers }}
          path: cypress/reports

  report:
    needs: test
    if: always() && needs.test.result != 'skipped'
    runs-on: ubuntu-latest
    container: cypress/browsers:node18.12.0-chrome107-ff106
    steps:
      - name: Download workspace
        uses: actions/download-artifact@v3
        with:
          name: workspace
          path: .
      - name: Download all test results
        uses: actions/download-artifact@v3
        with:
          path: test-results
      - name: Generate HTML report
        run: |
          npx mochawesome-merge 'test-results/test-results-*/cypress/reports/*.json' > merged-report.json
          npx mochawesome-report-generator merged-report.json --reportDir mochawesome-report
      - name: Upload consolidated report
        uses: actions/upload-artifact@v3
        with:
          name: cypress-test-report
          path: mochawesome-report
