name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - name: Install dependencies
        run: npm ci
      - name: Check types
        run: npx tsc --noEmit
      - name: Lint check
        run: npm run lint
      - name: Prettier check
        run: npx prettier --check .

  install:
    runs-on: ubuntu-latest
    container: cypress/browsers:node18.12.0-chrome107
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ~/.cache/Cypress
          key: cypress-${{ hashFiles('package-lock.json') }}
          restore-keys: cypress-
      - name: Install dependencies
        run: npm ci
      - name: Verify Cypress
        run: npx cypress verify

  test:
    needs: [check, install]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4]
        browsers: [chrome, firefox, edge]
    container: cypress/browsers:node18.12.0-chrome107-ff106
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ~/.cache/Cypress
          key: cypress-${{ hashFiles('package-lock.json') }}
          restore-keys: cypress-
      - name: Install dependencies
        run: npm ci
      - name: Run Cypress tests
        env:
          CYPRESS_AUTOMATENOW_URL: ${{ secrets.AUTOMATENOW_URL }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SPLIT: ${{ strategy.job-total }}
          SPLIT_INDEX: ${{ strategy.job-index }}
        run: npx cypress run --browser ${{ matrix.browsers }} --parallel --record --key ${{ secrets.CYPRESS_RECORD_KEY }}

  report:
    needs: test
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: actions/checkout@v4
      - name: Download test artifacts
        uses: actions/download-artifact@v3
        with:
          path: cypress/reports
      - name: Generate HTML report
        run: |
          npm ci
          npx mochawesome-merge cypress/reports/*.json > cypress/reports/output.json
          npx mochawesome-report-generator cypress/reports/output.json
      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: cypress-test-report
          path: mochawesome-report
